language: python
python:
  - 2.7
  - 3.5
sudo: false
cache:
  directories:
  - "~/.cache/pip"
env:
  - TOXENV=py27
  - TOXENV=py35
install:
  - pip install tox codecov
script:
  - tox -v
after_success:
- codecov
